//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="BrugeradminImplPortBinding", Namespace="http://soap.transport.brugerautorisation/")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(sendEmailResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(sendEmail))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(sendGlemtAdgangskodeEmailResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(sendGlemtAdgangskodeEmail))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ændrAdgangskodeResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ændrAdgangskode))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(hentBrugerOffentligtResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(hentBrugerOffentligt))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(hentBrugerResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(hentBruger))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(fjernAlleEkstraFelterResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(fjernAlleEkstraFelter))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(setEkstraFeltResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(setEkstraFelt))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getEkstraFeltResponse))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(getEkstraFelt))]
public partial class BrugeradminImplService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback hentBrugerOffentligtOperationCompleted;
    
    private System.Threading.SendOrPostCallback hentBrugerOperationCompleted;
    
    private System.Threading.SendOrPostCallback ændrAdgangskodeOperationCompleted;
    
    private System.Threading.SendOrPostCallback sendGlemtAdgangskodeEmailOperationCompleted;
    
    private System.Threading.SendOrPostCallback sendEmailOperationCompleted;
    
    private System.Threading.SendOrPostCallback getEkstraFeltOperationCompleted;
    
    private System.Threading.SendOrPostCallback setEkstraFeltOperationCompleted;
    
    private System.Threading.SendOrPostCallback fjernAlleEkstraFelterOperationCompleted;
    
    /// <remarks/>
    public BrugeradminImplService() {
        this.Url = "http://javabog.dk:9901/brugeradmin";
    }
    
    /// <remarks/>
    public event hentBrugerOffentligtCompletedEventHandler hentBrugerOffentligtCompleted;
    
    /// <remarks/>
    public event hentBrugerCompletedEventHandler hentBrugerCompleted;
    
    /// <remarks/>
    public event ændrAdgangskodeCompletedEventHandler ændrAdgangskodeCompleted;
    
    /// <remarks/>
    public event sendGlemtAdgangskodeEmailCompletedEventHandler sendGlemtAdgangskodeEmailCompleted;
    
    /// <remarks/>
    public event sendEmailCompletedEventHandler sendEmailCompleted;
    
    /// <remarks/>
    public event getEkstraFeltCompletedEventHandler getEkstraFeltCompleted;
    
    /// <remarks/>
    public event setEkstraFeltCompletedEventHandler setEkstraFeltCompleted;
    
    /// <remarks/>
    public event fjernAlleEkstraFelterCompletedEventHandler fjernAlleEkstraFelterCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.transport.brugerautorisation/", ResponseNamespace="http://soap.transport.brugerautorisation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bruger hentBrugerOffentligt([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0) {
        object[] results = this.Invoke("hentBrugerOffentligt", new object[] {
                    arg0});
        return ((bruger)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginhentBrugerOffentligt(string arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("hentBrugerOffentligt", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public bruger EndhentBrugerOffentligt(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bruger)(results[0]));
    }
    
    /// <remarks/>
    public void hentBrugerOffentligtAsync(string arg0) {
        this.hentBrugerOffentligtAsync(arg0, null);
    }
    
    /// <remarks/>
    public void hentBrugerOffentligtAsync(string arg0, object userState) {
        if ((this.hentBrugerOffentligtOperationCompleted == null)) {
            this.hentBrugerOffentligtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhentBrugerOffentligtOperationCompleted);
        }
        this.InvokeAsync("hentBrugerOffentligt", new object[] {
                    arg0}, this.hentBrugerOffentligtOperationCompleted, userState);
    }
    
    private void OnhentBrugerOffentligtOperationCompleted(object arg) {
        if ((this.hentBrugerOffentligtCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.hentBrugerOffentligtCompleted(this, new hentBrugerOffentligtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.transport.brugerautorisation/", ResponseNamespace="http://soap.transport.brugerautorisation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bruger hentBruger([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1) {
        object[] results = this.Invoke("hentBruger", new object[] {
                    arg0,
                    arg1});
        return ((bruger)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginhentBruger(string arg0, string arg1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("hentBruger", new object[] {
                    arg0,
                    arg1}, callback, asyncState);
    }
    
    /// <remarks/>
    public bruger EndhentBruger(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bruger)(results[0]));
    }
    
    /// <remarks/>
    public void hentBrugerAsync(string arg0, string arg1) {
        this.hentBrugerAsync(arg0, arg1, null);
    }
    
    /// <remarks/>
    public void hentBrugerAsync(string arg0, string arg1, object userState) {
        if ((this.hentBrugerOperationCompleted == null)) {
            this.hentBrugerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhentBrugerOperationCompleted);
        }
        this.InvokeAsync("hentBruger", new object[] {
                    arg0,
                    arg1}, this.hentBrugerOperationCompleted, userState);
    }
    
    private void OnhentBrugerOperationCompleted(object arg) {
        if ((this.hentBrugerCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.hentBrugerCompleted(this, new hentBrugerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.transport.brugerautorisation/", ResponseNamespace="http://soap.transport.brugerautorisation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bruger ændrAdgangskode([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2) {
        object[] results = this.Invoke("ændrAdgangskode", new object[] {
                    arg0,
                    arg1,
                    arg2});
        return ((bruger)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginændrAdgangskode(string arg0, string arg1, string arg2, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ændrAdgangskode", new object[] {
                    arg0,
                    arg1,
                    arg2}, callback, asyncState);
    }
    
    /// <remarks/>
    public bruger EndændrAdgangskode(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bruger)(results[0]));
    }
    
    /// <remarks/>
    public void ændrAdgangskodeAsync(string arg0, string arg1, string arg2) {
        this.ændrAdgangskodeAsync(arg0, arg1, arg2, null);
    }
    
    /// <remarks/>
    public void ændrAdgangskodeAsync(string arg0, string arg1, string arg2, object userState) {
        if ((this.ændrAdgangskodeOperationCompleted == null)) {
            this.ændrAdgangskodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnændrAdgangskodeOperationCompleted);
        }
        this.InvokeAsync("ændrAdgangskode", new object[] {
                    arg0,
                    arg1,
                    arg2}, this.ændrAdgangskodeOperationCompleted, userState);
    }
    
    private void OnændrAdgangskodeOperationCompleted(object arg) {
        if ((this.ændrAdgangskodeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ændrAdgangskodeCompleted(this, new ændrAdgangskodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.transport.brugerautorisation/", ResponseNamespace="http://soap.transport.brugerautorisation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void sendGlemtAdgangskodeEmail([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1) {
        this.Invoke("sendGlemtAdgangskodeEmail", new object[] {
                    arg0,
                    arg1});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsendGlemtAdgangskodeEmail(string arg0, string arg1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sendGlemtAdgangskodeEmail", new object[] {
                    arg0,
                    arg1}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndsendGlemtAdgangskodeEmail(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void sendGlemtAdgangskodeEmailAsync(string arg0, string arg1) {
        this.sendGlemtAdgangskodeEmailAsync(arg0, arg1, null);
    }
    
    /// <remarks/>
    public void sendGlemtAdgangskodeEmailAsync(string arg0, string arg1, object userState) {
        if ((this.sendGlemtAdgangskodeEmailOperationCompleted == null)) {
            this.sendGlemtAdgangskodeEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendGlemtAdgangskodeEmailOperationCompleted);
        }
        this.InvokeAsync("sendGlemtAdgangskodeEmail", new object[] {
                    arg0,
                    arg1}, this.sendGlemtAdgangskodeEmailOperationCompleted, userState);
    }
    
    private void OnsendGlemtAdgangskodeEmailOperationCompleted(object arg) {
        if ((this.sendGlemtAdgangskodeEmailCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sendGlemtAdgangskodeEmailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.transport.brugerautorisation/", ResponseNamespace="http://soap.transport.brugerautorisation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void sendEmail([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg3) {
        this.Invoke("sendEmail", new object[] {
                    arg0,
                    arg1,
                    arg2,
                    arg3});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsendEmail(string arg0, string arg1, string arg2, string arg3, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sendEmail", new object[] {
                    arg0,
                    arg1,
                    arg2,
                    arg3}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndsendEmail(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void sendEmailAsync(string arg0, string arg1, string arg2, string arg3) {
        this.sendEmailAsync(arg0, arg1, arg2, arg3, null);
    }
    
    /// <remarks/>
    public void sendEmailAsync(string arg0, string arg1, string arg2, string arg3, object userState) {
        if ((this.sendEmailOperationCompleted == null)) {
            this.sendEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendEmailOperationCompleted);
        }
        this.InvokeAsync("sendEmail", new object[] {
                    arg0,
                    arg1,
                    arg2,
                    arg3}, this.sendEmailOperationCompleted, userState);
    }
    
    private void OnsendEmailOperationCompleted(object arg) {
        if ((this.sendEmailCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sendEmailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.transport.brugerautorisation/", ResponseNamespace="http://soap.transport.brugerautorisation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object getEkstraFelt([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2) {
        object[] results = this.Invoke("getEkstraFelt", new object[] {
                    arg0,
                    arg1,
                    arg2});
        return ((object)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetEkstraFelt(string arg0, string arg1, string arg2, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getEkstraFelt", new object[] {
                    arg0,
                    arg1,
                    arg2}, callback, asyncState);
    }
    
    /// <remarks/>
    public object EndgetEkstraFelt(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((object)(results[0]));
    }
    
    /// <remarks/>
    public void getEkstraFeltAsync(string arg0, string arg1, string arg2) {
        this.getEkstraFeltAsync(arg0, arg1, arg2, null);
    }
    
    /// <remarks/>
    public void getEkstraFeltAsync(string arg0, string arg1, string arg2, object userState) {
        if ((this.getEkstraFeltOperationCompleted == null)) {
            this.getEkstraFeltOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEkstraFeltOperationCompleted);
        }
        this.InvokeAsync("getEkstraFelt", new object[] {
                    arg0,
                    arg1,
                    arg2}, this.getEkstraFeltOperationCompleted, userState);
    }
    
    private void OngetEkstraFeltOperationCompleted(object arg) {
        if ((this.getEkstraFeltCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getEkstraFeltCompleted(this, new getEkstraFeltCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.transport.brugerautorisation/", ResponseNamespace="http://soap.transport.brugerautorisation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void setEkstraFelt([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg2, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] object arg3) {
        this.Invoke("setEkstraFelt", new object[] {
                    arg0,
                    arg1,
                    arg2,
                    arg3});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsetEkstraFelt(string arg0, string arg1, string arg2, object arg3, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("setEkstraFelt", new object[] {
                    arg0,
                    arg1,
                    arg2,
                    arg3}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndsetEkstraFelt(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void setEkstraFeltAsync(string arg0, string arg1, string arg2, object arg3) {
        this.setEkstraFeltAsync(arg0, arg1, arg2, arg3, null);
    }
    
    /// <remarks/>
    public void setEkstraFeltAsync(string arg0, string arg1, string arg2, object arg3, object userState) {
        if ((this.setEkstraFeltOperationCompleted == null)) {
            this.setEkstraFeltOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetEkstraFeltOperationCompleted);
        }
        this.InvokeAsync("setEkstraFelt", new object[] {
                    arg0,
                    arg1,
                    arg2,
                    arg3}, this.setEkstraFeltOperationCompleted, userState);
    }
    
    private void OnsetEkstraFeltOperationCompleted(object arg) {
        if ((this.setEkstraFeltCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.setEkstraFeltCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://soap.transport.brugerautorisation/", ResponseNamespace="http://soap.transport.brugerautorisation/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public void fjernAlleEkstraFelter([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg0, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string arg1) {
        this.Invoke("fjernAlleEkstraFelter", new object[] {
                    arg0,
                    arg1});
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfjernAlleEkstraFelter(string arg0, string arg1, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("fjernAlleEkstraFelter", new object[] {
                    arg0,
                    arg1}, callback, asyncState);
    }
    
    /// <remarks/>
    public void EndfjernAlleEkstraFelter(System.IAsyncResult asyncResult) {
        this.EndInvoke(asyncResult);
    }
    
    /// <remarks/>
    public void fjernAlleEkstraFelterAsync(string arg0, string arg1) {
        this.fjernAlleEkstraFelterAsync(arg0, arg1, null);
    }
    
    /// <remarks/>
    public void fjernAlleEkstraFelterAsync(string arg0, string arg1, object userState) {
        if ((this.fjernAlleEkstraFelterOperationCompleted == null)) {
            this.fjernAlleEkstraFelterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfjernAlleEkstraFelterOperationCompleted);
        }
        this.InvokeAsync("fjernAlleEkstraFelter", new object[] {
                    arg0,
                    arg1}, this.fjernAlleEkstraFelterOperationCompleted, userState);
    }
    
    private void OnfjernAlleEkstraFelterOperationCompleted(object arg) {
        if ((this.fjernAlleEkstraFelterCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.fjernAlleEkstraFelterCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.transport.brugerautorisation/")]
public partial class bruger {
    
    private string brugernavnField;
    
    private string emailField;
    
    private long sidstAktivField;
    
    private string campusnetIdField;
    
    private string studeretningField;
    
    private string fornavnField;
    
    private string efternavnField;
    
    private string adgangskodeField;
    
    private brugerEntry[] ekstraFelterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string brugernavn {
        get {
            return this.brugernavnField;
        }
        set {
            this.brugernavnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long sidstAktiv {
        get {
            return this.sidstAktivField;
        }
        set {
            this.sidstAktivField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string campusnetId {
        get {
            return this.campusnetIdField;
        }
        set {
            this.campusnetIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string studeretning {
        get {
            return this.studeretningField;
        }
        set {
            this.studeretningField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fornavn {
        get {
            return this.fornavnField;
        }
        set {
            this.fornavnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string efternavn {
        get {
            return this.efternavnField;
        }
        set {
            this.efternavnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string adgangskode {
        get {
            return this.adgangskodeField;
        }
        set {
            this.adgangskodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("entry", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public brugerEntry[] ekstraFelter {
        get {
            return this.ekstraFelterField;
        }
        set {
            this.ekstraFelterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.transport.brugerautorisation/")]
public partial class brugerEntry {
    
    private string keyField;
    
    private object valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string key {
        get {
            return this.keyField;
        }
        set {
            this.keyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.transport.brugerautorisation/")]
public partial class sendEmailResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.transport.brugerautorisation/")]
public partial class sendEmail {
    
    private string arg0Field;
    
    private string arg1Field;
    
    private string arg2Field;
    
    private string arg3Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0 {
        get {
            return this.arg0Field;
        }
        set {
            this.arg0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg1 {
        get {
            return this.arg1Field;
        }
        set {
            this.arg1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg2 {
        get {
            return this.arg2Field;
        }
        set {
            this.arg2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg3 {
        get {
            return this.arg3Field;
        }
        set {
            this.arg3Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.transport.brugerautorisation/")]
public partial class sendGlemtAdgangskodeEmailResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.transport.brugerautorisation/")]
public partial class sendGlemtAdgangskodeEmail {
    
    private string arg0Field;
    
    private string arg1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0 {
        get {
            return this.arg0Field;
        }
        set {
            this.arg0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg1 {
        get {
            return this.arg1Field;
        }
        set {
            this.arg1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.transport.brugerautorisation/")]
public partial class ændrAdgangskodeResponse {
    
    private bruger returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bruger @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.transport.brugerautorisation/")]
public partial class ændrAdgangskode {
    
    private string arg0Field;
    
    private string arg1Field;
    
    private string arg2Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0 {
        get {
            return this.arg0Field;
        }
        set {
            this.arg0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg1 {
        get {
            return this.arg1Field;
        }
        set {
            this.arg1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg2 {
        get {
            return this.arg2Field;
        }
        set {
            this.arg2Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.transport.brugerautorisation/")]
public partial class hentBrugerOffentligtResponse {
    
    private bruger returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bruger @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.transport.brugerautorisation/")]
public partial class hentBrugerOffentligt {
    
    private string arg0Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0 {
        get {
            return this.arg0Field;
        }
        set {
            this.arg0Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.transport.brugerautorisation/")]
public partial class hentBrugerResponse {
    
    private bruger returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bruger @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.transport.brugerautorisation/")]
public partial class hentBruger {
    
    private string arg0Field;
    
    private string arg1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0 {
        get {
            return this.arg0Field;
        }
        set {
            this.arg0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg1 {
        get {
            return this.arg1Field;
        }
        set {
            this.arg1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.transport.brugerautorisation/")]
public partial class fjernAlleEkstraFelterResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.transport.brugerautorisation/")]
public partial class fjernAlleEkstraFelter {
    
    private string arg0Field;
    
    private string arg1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0 {
        get {
            return this.arg0Field;
        }
        set {
            this.arg0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg1 {
        get {
            return this.arg1Field;
        }
        set {
            this.arg1Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.transport.brugerautorisation/")]
public partial class setEkstraFeltResponse {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.transport.brugerautorisation/")]
public partial class setEkstraFelt {
    
    private string arg0Field;
    
    private string arg1Field;
    
    private string arg2Field;
    
    private object arg3Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0 {
        get {
            return this.arg0Field;
        }
        set {
            this.arg0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg1 {
        get {
            return this.arg1Field;
        }
        set {
            this.arg1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg2 {
        get {
            return this.arg2Field;
        }
        set {
            this.arg2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object arg3 {
        get {
            return this.arg3Field;
        }
        set {
            this.arg3Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.transport.brugerautorisation/")]
public partial class getEkstraFeltResponse {
    
    private object returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object @return {
        get {
            return this.returnField;
        }
        set {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.transport.brugerautorisation/")]
public partial class getEkstraFelt {
    
    private string arg0Field;
    
    private string arg1Field;
    
    private string arg2Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0 {
        get {
            return this.arg0Field;
        }
        set {
            this.arg0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg1 {
        get {
            return this.arg1Field;
        }
        set {
            this.arg1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg2 {
        get {
            return this.arg2Field;
        }
        set {
            this.arg2Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void hentBrugerOffentligtCompletedEventHandler(object sender, hentBrugerOffentligtCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class hentBrugerOffentligtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal hentBrugerOffentligtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bruger Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bruger)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void hentBrugerCompletedEventHandler(object sender, hentBrugerCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class hentBrugerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal hentBrugerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bruger Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bruger)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void ændrAdgangskodeCompletedEventHandler(object sender, ændrAdgangskodeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ændrAdgangskodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ændrAdgangskodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bruger Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bruger)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void sendGlemtAdgangskodeEmailCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void sendEmailCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void getEkstraFeltCompletedEventHandler(object sender, getEkstraFeltCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getEkstraFeltCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getEkstraFeltCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public object Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((object)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void setEkstraFeltCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void fjernAlleEkstraFelterCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
